#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zopfli
Version  : 1.0.1
Release  : 1
URL      : https://github.com/google/zopfli/archive/zopfli-1.0.1.tar.gz
Source0  : https://github.com/google/zopfli/archive/zopfli-1.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: zopfli-lib
Patch1: build.patch

%description
Zopfli Compression Algorithm is a compression library programmed in C to perform
very good, but slow, deflate or zlib compression.

%package dev
Summary: dev components for the zopfli package.
Group: Development
Requires: zopfli-lib
Provides: zopfli-devel

%description dev
dev components for the zopfli package.


%package lib
Summary: lib components for the zopfli package.
Group: Libraries

%description lib
lib components for the zopfli package.


%prep
%setup -q -n zopfli-zopfli-1.0.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507858175
make V=1  %{?_smp_mflags} libzopfli

%install
export SOURCE_DATE_EPOCH=1507858175
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libzopfli.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzopfli.so.1
/usr/lib64/libzopfli.so.1.0.1
