#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zopfli
Version  : 1.0.2
Release  : 6
URL      : https://github.com/google/zopfli/archive/zopfli-1.0.2.tar.gz
Source0  : https://github.com/google/zopfli/archive/zopfli-1.0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: zopfli-lib = %{version}-%{release}
Requires: zopfli-license = %{version}-%{release}
Patch1: build.patch
Patch2: defaults.patch

%description
Zopfli Compression Algorithm is a compression library programmed in C to perform
very good, but slow, deflate or zlib compression.

%package dev
Summary: dev components for the zopfli package.
Group: Development
Requires: zopfli-lib = %{version}-%{release}
Provides: zopfli-devel = %{version}-%{release}

%description dev
dev components for the zopfli package.


%package lib
Summary: lib components for the zopfli package.
Group: Libraries
Requires: zopfli-license = %{version}-%{release}

%description lib
lib components for the zopfli package.


%package license
Summary: license components for the zopfli package.
Group: Default

%description license
license components for the zopfli package.


%prep
%setup -q -n zopfli-zopfli-1.0.2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551308106
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags} libzopfli DEFAULTFLAGS="$CFLAGS"


%install
export SOURCE_DATE_EPOCH=1551308106
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zopfli
cp COPYING %{buildroot}/usr/share/package-licenses/zopfli/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libzopfli.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzopfli.so.1
/usr/lib64/libzopfli.so.1.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zopfli/COPYING
